### ISSUE TITLE
is a bluetooth adpater available on raspberry pi 3

### ISSUE THREAD

**Issue by uowis** [mjmccans/hassio-addon-airthings#5] opened 2022-03-24 14:03 UTC
Sorry perhaps it's a newbe problem but i don"t found solution anywhere there is the log : 
`
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:50:40] INFO: Getting mqtt configuration...
[14:50:44] INFO: Starting python script...
[2022-03-24 14:50:46] WARNING: Invalid mac address provided: 
[2022-03-24 14:50:46] INFO: Setting up Airthings sensors...
[2022-03-24 14:50:46] INFO: No devices provided, so searching for Airthings sensors...
[2022-03-24 14:50:46] INFO: Starting search for Airthings sensors...
[2022-03-24 14:50:47] ERROR: Failed while searching for devices. Is a bluetooth adapter available? If the watchdog option is enabled, this addon will restart and try again.
Traceback (most recent call last):
  File "/src/./airthings-mqtt.ha.py", line 72, in find_devices
    num_devices_found = self.airthingsdetect.find_devices()
  File "/src/airthings.py", line 236, in find_devices
    advertisements = scanner.scan(timeout)
  File "/usr/local/lib/python3.9/dist-packages/bluepy/btle.py", line 852, in scan
    self.start(passive=passive)
  File "/usr/local/lib/python3.9/dist-packages/bluepy/btle.py", line 797, in start
    self._mgmtCmd(self._cmd()+"end")
  File "/usr/local/lib/python3.9/dist-packages/bluepy/btle.py", line 312, in _mgmtCmd
    raise BTLEManagementError("Failed to execute management command '%s'" % (cmd), rsp)
bluepy.btle.BTLEManagementError: Failed to execute management command 'scanend' (code: 13, error: Invalid Parameters)
[cmd] ./run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
`

**Comment by mjmccans** [comment] 2022-03-29 15:13
Sorry for the delay getting back to you. I am not exactly sure what the issue is, but it looks like it is not related to this add on and may be either the bluetooth adapter is not on/enabled or there is a permissions issue to access the adapter. I am not running my Home Assistant on a Raspberry Pi so unfortunately I cannot test this out for you, but some Googling suggests that you are not the only person having similar issues with bluetooth (see [here](https://community.home-assistant.io/t/ha-raspberry-pi-4-bluetooth-not-working/384999) for an example). Hopefully something from that discussion helps you out. For now I am going to close this issue because it does not look related to this add on, but if you do some digging and find out otherwise we can reopen it. Good luck!

**Closed as completed by mjmccans** 2022-03-29 15:13 UTC

**Comment by uowis** [comment] 2022-03-30 11:11
Sorry i have found mac adresse with other App and all is okay. I have my sensor ! Thanks and congrate for this add !

**Comment by mjmccans** [comment] 2022-03-30 12:44
I am happy that you were able to find the mac addresses with another app, but I would like to know why the addon was not working for you. Perhaps I will explore this a bit more when I am making whatever is the next update.

**Comment by uowis** [comment] 2022-05-05 08:04
I have trouble looking, same bug : 
` ERROR: Failed while searching for devices. Is a bluetooth adapter available? If the watchdog option is enabled, this addon will restart and try again.`
but my bluetooth is okay : 
`[bluetooth]# show
Controller B8:27:EB:E3:77:15 (public)
        Name: homeassistant
        Alias: homeassistant
        Class: 0x00200000
        Powered: yes
        Discoverable: no
        DiscoverableTimeout: 0x000000b4
        Pairable: no
        UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
        UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
        UUID: Headset                   (00001108-0000-1000-8000-00805f9b34fb)
        UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
        UUID: Headset AG                (00001112-0000-1000-8000-00805f9b34fb)
        UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
        Modalias: usb:v1D6Bp0246d053E
        Discovering: no
        Roles: central
        Roles: peripheral
Advertising Features:
        ActiveInstances: 0x00 (0)
        SupportedInstances: 0x05 (5)
        SupportedIncludes: tx-power
        SupportedIncludes: appearance
        SupportedIncludes: local-name
`

**Comment by uowis** [comment] 2022-05-06 09:40
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:38:08] INFO: Internal MQTT service found, fetching configuration ...
[11:38:11] INFO: Starting python script...
[2022-05-06 11:38:12] WARNING: Invalid mac address provided: 
[2022-05-06 11:38:12] INFO: Setting up Airthings sensors...
[2022-05-06 11:38:12] INFO: No devices provided, so searching for Airthings sensors...
[2022-05-06 11:38:12] INFO: Starting search for Airthings sensors...
[2022-05-06 11:38:12] ERROR: Failed while searching for devices. Is a bluetooth adapter available? If the watchdog option is enabled, this addon will restart and try again.
Traceback (most recent call last):
  File "/src/./airthings-mqtt.ha.py", line 72, in find_devices
    num_devices_found = self.airthingsdetect.find_devices()
  File "/src/airthings.py", line 236, in find_devices
    advertisements = scanner.scan(timeout)
  File "/usr/local/lib/python3.9/dist-packages/bluepy/btle.py", line 854, in scan
    self.stop()
  File "/usr/local/lib/python3.9/dist-packages/bluepy/btle.py", line 803, in stop
    self._mgmtCmd(self._cmd()+"end")
  File "/usr/local/lib/python3.9/dist-packages/bluepy/btle.py", line 312, in _mgmtCmd
    raise BTLEManagementError("Failed to execute management command '%s'" % (cmd), rsp)
bluepy.btle.BTLEManagementError: Failed to execute management command 'scanend' (code: 11, error: Rejected)
[cmd] ./run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

**Comment by uowis** [comment] 2022-05-09 08:39
and i have this lo with good MAC address in configuration : 
`

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> [10:36:32] INFO: Internal MQTT service found, fetching configuration ...
> [10:36:35] INFO: Starting python script...
> [2022-05-09 10:36:36] INFO: Setting up Airthings sensors...
> [2022-05-09 10:36:36] DEBUG: Getting info about device(s)...
> [2022-05-09 10:36:36] DEBUG: Getting sensors...
> [2022-05-09 10:36:37] INFO: Done Airthings setup.
> [2022-05-09 10:36:37] DEBUG: Getting sensor data...
> [2022-05-09 10:36:37] ERROR: No sensor values collected. Please check your configuration and make sure your bluetooth adapter is available. If the watchdog option is enabled, this addon will restart and try again.
> [cmd] ./run.sh exited 1
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-finish] sending all processes the TERM signal.

`
i could connect with device with bluetoothctrl command

**Comment by mjmccans** [comment] 2022-05-09 17:14
This is a strange error, and it is interesting that the script does not work but accessing the bluetooth adapter and the Airthings device from a terminal does. Can you please run the script with log_level = DEBUG and without any devices listed in the configuration? I would like to see what lines are output to better understand where it fails. I am also going to release a new version shortly, and if this does not work I can add some additional debug outputs in the next version to help narrow down the cause even further. Thank you.

**Comment by uowis** [comment] 2022-05-14 07:52
OKay i have found old mouse bluetooth dongle and all is okay. It was material bug. Congrate for this integration ! I have all sensor,.. perfect!

**Comment by uowis** [comment] 2022-07-19 21:47
"No sensor values collected. Please check your configuration and make sure your bluetooth adapter is available." 
while platform: bluetooth_le_tracker detect airthings device ,...

**Comment by uowis** [comment] 2022-07-19 21:48
same error without "with log_level = DEBUG and without any devices listed in the configuration"

**Comment by uowis** [comment] 2022-07-19 21:59
with log_level = DEBUG and without any devices listed in the configuration

i have 
`[23:56:05] INFO: Internal MQTT service found, fetching configuration ...
[23:56:08] INFO: Starting python script...
[2022-07-19 23:56:08] WARNING: Invalid mac address provided: 
[2022-07-19 23:56:08] INFO: Setting up Airthings sensors...
[2022-07-19 23:56:08] INFO: No devices provided, so searching for Airthings sensors...
[2022-07-19 23:56:08] INFO: Starting search for Airthings sensors...
[2022-07-19 23:56:16] INFO: Found 1 airthings device(s).
---------------------------------
Your suggested add-on yaml configuration is below:
 
devices:
  - mac: d8:71:4d:96:c3:50
    name: Insert Device Name
refresh_interval: 150
retry_count: 10
retry_wait: 3
log_level: INFO
mqtt_discovery: 'true'
 
---------------------------------
[23:56:16] INFO: Done.`

So i try with simply copy/paste in configuration but same bug : 
"No sensor values collected. Please check your configuration and make sure your bluetooth adapter is available."

**Comment by mjmccans** [comment] 2022-07-20 11:47
I am not sure what is causing your error, but I do have an update in the works that changes the bluetooth library the addon uses to a more modern one and I am hoping that will fix some of these issues or make it easier to debug them. I am hoping to release it next week.

**Comment by uowis** [comment] 2022-07-22 07:11
great, I'm on the lookout!
just one more note, when airthing addon work ble tracker don"t detect airthings device...
